Support onbuild instruction
chainguard-dev/apko pull request #635
Opened 2023-04-23 21:53 UTC by mesaglio

Hi!

With this onbuild instruction support we can add behavior to the apko images when we use them as base images.

2023-04-27 14:32 UTC, mesaglio commented
Hi! @imjasonh @kaniini, can you help me with this pr?

2023-05-01 15:39 UTC, kaniini requested changes
In general, I don't think we should encourage doing this, but it seems fine.

2023-05-01 15:39 UTC, kaniini commented on pkg/build/types/build_option.go
> +	OnBuild    []string        `yaml:"on_build,omitempty"`
```suggestion
	OnBuild    []string        `yaml:"on-build,omitempty"`
```

2023-05-01 15:39 UTC, kaniini commented on pkg/build/types/image_configuration.go
> +		logger.Printf("  on_build:")
```suggestion
		logger.Printf("  on-build:")
```

2023-05-01 15:39 UTC, kaniini commented on pkg/build/types/image_configuration.go
> +		for _, onBuildInstruccion := range ic.OnBuild {
```suggestion
		for _, onBuildInstruction := range ic.OnBuild {
```

2023-05-01 15:39 UTC, kaniini commented on pkg/build/types/image_configuration.go
> +			logger.Printf("    - %s", onBuildInstruccion)
```suggestion
			logger.Printf("    - %s", onBuildInstruction)
```

2023-05-01 21:09 UTC, imjasonh commented
I'm a little curious to learn more about your use case. Do you have an example scenario in mind? I thought `ONBUILD` instructions in Dockerfiles were deprecated and recommended against for quite some time, but maybe I'm mistaken.

2023-05-01 23:22 UTC, mesaglio commented
Hello @imjasonh, I did not find in the official docker documentation that the onbuild instructions had been deprecated but I will look for it.

One use case we are looking at is having a distroless image for production and another in the development stage. Seeking that the environment is not so different, we think that the development environment is the production environment + busybox + compilation.
I thought some dockerfile with this style
```dockerfile
FROM prod_img:latest
# this can be added with melango + apko
RUN apk add busybox
ONBUILD COPY . /app
WORKDIR /app
ONBUILD CMD ["python3", "-m", "app"]
```

Final Dockerfile that devs can use
```dockerfile
FROM dev_img:latest
```

2023-09-04 00:23 UTC, mesaglio commented
This have no sense 😢

2023-09-04 00:23 UTC, closed without merging

2025-01-20 19:34 UTC, mfortin commented
@mesaglio did you find an alternative ?
I was looking for this feature too

2025-01-20 19:53 UTC, mesaglio commented
No I dont. But I understand that `ONBUILD` instruction is in [Docker image spec](https://github.com/moby/docker-image-spec/blob/v1.2.0/v1.2.md) no in [OCI image spec](https://specs.opencontainers.org/image-spec/config/?v=v1.0.1)